
name: Compilar APK Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
          packages: ''

      - name: Aceptar licencias Android
        run: yes | sdkmanager --licenses || true

      - name: Comprobar estructura
        run: |
          ls -la
          ls -la proj

      - name: Dar permisos a Gradle
        working-directory: proj
        run: chmod +x gradlew

      - name: Compilar APK
        working-directory: proj
        run: ./gradlew assembleDebug --no-daemon

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: DACATECH-APK
          path: proj/app/build/outputs/apk/debug/*.apk
